env-var-prefix: "RANK"

app_salt: "some_random_str"

static_path: "./static"
entry_file: "./index.html"

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "wechat_rank"

redis:
  address: "127.0.0.1"
  port: "6379"

qingbo:
  appid: ""
  appkey: ""
  groupid: "105638"

ticket:
  driver: "redis"
  ttl: 2592000